defmodule SparkEx.Test.ParitySmokeTest do
  @moduledoc """
  Drives `SparkEx.Test.ParitySmoke` against fixtures generated by
  `test/spark_server/parity_smoke.py`.

  ## Tagging

  Parity assertions are tagged `:parity_smoke` and excluded from the
  default `mix test` run (see `test/test_helper.exs`) because they
  require fixtures produced against a live Spark Connect server. Run
  them explicitly:

      cd test/spark_server
      SPARK_REMOTE=sc://localhost:15002 uv run python parity_smoke.py
      cd -
      mix test --include parity_smoke

  Missing fixtures fail the tagged test with setup instructions rather
  than silently passing — that way CI can't drift away from upstream
  parity without someone noticing.

  The normalize/1 unit tests don't need fixtures and always run.
  """

  use ExUnit.Case, async: true

  alias SparkEx.{DataFrame, Functions, Column}
  alias SparkEx.Test.ParitySmoke

  defp build_chain("sql_simple") do
    {:sql, "SELECT 1 AS x", nil}
  end

  defp build_chain("select_filter") do
    df = %DataFrame{session: self(), plan: {:sql, "SELECT id, name FROM tbl", nil}}

    df
    |> DataFrame.filter(Column.gt(Functions.col("id"), Functions.lit(10)))
    |> DataFrame.select([
      Functions.col("name"),
      Column.alias_(Column.plus(Functions.col("id"), Functions.lit(1)), "id1")
    ])
    |> Map.fetch!(:plan)
  end

  defp build_chain("join_on_columns") do
    left = %DataFrame{session: self(), plan: {:sql, "SELECT id, dept_id FROM emp", nil}}
    right = %DataFrame{session: self(), plan: {:sql, "SELECT dept_id, name FROM dept", nil}}

    join_cond = Column.eq(DataFrame.col(left, "dept_id"), DataFrame.col(right, "dept_id"))

    DataFrame.join(left, right, join_cond, :inner)
    |> DataFrame.select([DataFrame.col(left, "id"), DataFrame.col(right, "name")])
    |> Map.fetch!(:plan)
  end

  test "normalize/1 strips plan_ids on RelationCommon" do
    plan = ParitySmoke.encode_normalized({:sql, "SELECT 1", nil})
    %Spark.Connect.Plan{op_type: {:root, rel}} = plan
    assert rel.common.plan_id == 0
  end

  test "normalize/1 strips :plan_id on any struct field, not just RelationCommon" do
    attr = %Spark.Connect.Expression.UnresolvedAttribute{
      unparsed_identifier: "x",
      plan_id: 42
    }

    regex = %Spark.Connect.Expression.UnresolvedRegex{col_name: "^x", plan_id: 99}
    star = %Spark.Connect.Expression.UnresolvedStar{plan_id: 7, unparsed_target: nil}

    assert %{plan_id: 0} = ParitySmoke.normalize(attr)
    assert %{plan_id: 0} = ParitySmoke.normalize(regex)
    assert %{plan_id: 0} = ParitySmoke.normalize(star)
  end

  for name <- ["sql_simple", "select_filter", "join_on_columns"] do
    @name name

    @tag :parity_smoke
    test "parity smoke: #{name}" do
      term = build_chain(@name)

      case ParitySmoke.load(@name) do
        {:error, :missing} ->
          flunk("""
          PySpark fixture missing: test/fixtures/parity_smoke/#{@name}.bin

          Generate fixtures against a running Spark Connect server:

              cd test/spark_server
              SPARK_REMOTE=sc://localhost:15002 uv run python parity_smoke.py

          Then re-run with `mix test --include parity_smoke`.
          """)

        {:ok, py_plan} ->
          py_normalized = ParitySmoke.normalize(py_plan)
          ex_normalized = ParitySmoke.encode_normalized(term)

          assert py_normalized == ex_normalized,
                 """
                 PySpark parity diff for #{@name}:
                 PySpark (normalized):
                 #{inspect(py_normalized, pretty: true, limit: :infinity)}

                 SparkEx (normalized):
                 #{inspect(ex_normalized, pretty: true, limit: :infinity)}
                 """
      end
    end
  end
end
